---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomeal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomeal
  template:
    metadata:
      labels:
        app: zomeal
    spec:
      containers:
      - name: zomeal
        image: sreedhar8897/zomeal:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: zomeal-service
spec:
  selector:
    app: zomeal
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
